name: Daily ML Trading Strategy
on:
  schedule:
    # Run at 4:05 PM ET (9:05 PM UTC) after market close
    - cron: '5 21 * * 1-5'  # Monday to Friday
  
  workflow_dispatch:  # Allow manual trigger
jobs:
  run-trading-strategy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.11'
        activate-environment: trading
        auto-activate-base: false
    
    - name: Install TA-Lib and dependencies
      shell: bash -el {0}
      run: |
        conda install -c conda-forge ta-lib -y
        pip install -r requirements.txt
    
    - name: Run Trading Analysis
      shell: bash -el {0}
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: |
        python trading_bot.py
    
    - name: Upload Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trading-results-${{ github.run_number }}
        path: |
          results/
          *.log
        retention-days: 30
    
    - name: Commit Results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        git add results/ || true
        git diff --staged --quiet || git commit -m "📊 Daily analysis results $(date +%Y-%m-%d)"
        git push || echo "Nothing to commit"
